 Version: 2.0
Env:
   Variable: 
      DOCKER_USERNAME:”SAIRAM”
      IMAGE_NAME: “nginx”
      IMAGE_TAG: “v1”
Parameter-store:
   DOCKER_PASSWORD: “docker_password”
Phases: 
   Pre-build:
    Commands: 
      - echo “Login  to docker “
     -  docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD 
  Build :
   Commands: 
      -  echo “ docker images build process “
     -   docker build -t  $IMAGE_NAME:$IMAGE_TAG
     -   docker tag $IMAGE_NAME:$IMAE_TAG  $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG 
 Post-build: 
  Commands: 
- echo “ build successfully completed”
- docker push $DOCKER_USERNAME/$IMAGE_NAME:IMAGE_TAG